# text_variables.py
# Текстовые переменные для тестирования ProBonus

class TextVariables:
    # Табличные ячейки (для playwright_expect)
    TABLE_CELL_PROJECT_NAME = "Название проекта:"
    TABLE_CELL_LICENSE_COUNT = "Количество лицензий:"
    TABLE_CELL_FEATURES = "Фичи:"
    TABLE_CELL_LICENSE_STATUS = "Статус лицензии:"
    TABLE_CELL_CONNECTION_STATUS = "Статус соединения с сервером лицензирования:"
    TABLE_CELL_LICENSE_END_DATE = "Дата окончания лицензии:"
    TABLE_CELL_CHECK_LICENSE = "Проверить лицензию"
    
    # Заголовки таблиц (columnheader)
    TABLE_CELL_OBJECT_NAME = "Название объекта:"
    TABLE_CELL_PROJECT_NAME = "Название проекта:"
    TABLE_CELL_LICENSE_COUNT = "Количество лицензий:"
    TABLE_CELL_FEATURES = "Фичи:"
    TABLE_CELL_LICENSE_STATUS = "Статус лицензии:"
    TABLE_CELL_CONNECTION_STATUS = "Статус соединения с сервером лицензирования:"
    TABLE_CELL_LICENSE_END_DATE = "Дата окончания лицензии:"
    TABLE_CELL_CHECK_LICENSE = "Проверить лицензию"
    
    # ЗАГОЛОВКИ ТАБЛИЦ - ПРАВИЛЬНЫЕ XPATH
    COLUMNHEADER_FIO = "//th[contains(@class, 'sortable')]//span[text()='ФИО']"
    COLUMNHEADER_PHONES = "//th[contains(@class, 'sortable')]//span[contains(text(), 'Телефоны')]"
    COLUMNHEADER_CARDS = "//th[contains(@class, 'sortable')]//span[text()='Идентификаторы: карты']"
    COLUMNHEADER_PHONES_ID = "//th[contains(@class, 'sortable')]//span[contains(translate(text(), 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ', 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'), 'идентификаторы: телефоны')]"
    COLUMNHEADER_OTHER_ID = "//th[contains(@class, 'sortable')]//span[contains(translate(text(), 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ', 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'), 'идентификаторы: другие')]"
    COLUMNHEADER_BALANCE = "//th[contains(@class, 'sortable')]//span[text()='Баланс']"
    COLUMNHEADER_ID = "//th[contains(@class, 'sortable')]//span[text()='id']"
    COLUMNHEADER_ID_CAPS="//th[contains(@class, 'sortable')]//span[contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'id')]"
    COLUMNHEADER_NAME = "//th[contains(@class, 'sortable')]//*[text()='Наименование']"
    COLUMNHEADER_TAG_NAME= "//th[contains(@class, 'sortable')]//*[text()='Название']"
    COLUMNHEADER_ACTION = "//th[@role='columnheader' and @aria-label='Действие']"
    COLUMNHEADER_LOGIN = "//th[contains(@class, 'sortable')]//span[text()='Логин']"
    COLUMNHEADER_ROLE = "//th[contains(@class, 'sortable')]//span[text()='Роль']"
    COLUMNHEADER_USER_TYPE = "//th[contains(@class, 'sortable')]//span[text()='Тип пользователя']"
    COLUMNHEADER_DISCOUNT_CODE = "//th[contains(@class, 'sortable')]//span[text()='Код скидки']"
    COLUMNHEADER_START_DATE = "//th[contains(@class, 'sortable')]//span[text()='Начало']"
    COLUMNHEADER_END_DATE = "//th[contains(@class, 'sortable')]//span[text()='Конец']"
    COLUMNHEADER_ACTION_TYPE = "//th[contains(@class, 'sortable')]//span[text()='Тип применения акции']"
    COLUMNHEADER_TOTAL_MESSAGES = "//th[contains(@class, 'sortable')]//span[text()='Общее число сообщений']"
    COLUMNHEADER_AWAITING_SEND = "//th[contains(@class, 'sortable')]//span[text()='Ожидает отправки']"
    COLUMNHEADER_SENT_MESSAGES = "//th[contains(@class, 'sortable')]//span[text()='Отправлено сообщений']"
    COLUMNHEADER_SEND_ERROR = "//th[contains(@class, 'sortable')]//span[text()='Ошибка отправки']"
    COLUMNHEADER_SEND_CANCELED = "//th[contains(@class, 'sortable')]//span[text()='Отправка отменена']"
    COLUMNHEADER_SEND_SPEED = "//th[contains(@class, 'sortable')]//span[text()='Скорость, шт/мин.']"
    COLUMNHEADER_END_DATETIME = "//th[contains(@class, 'sortable')]//span[text()='Дата/время окончания']"
    COLUMNHEADER_SUM = "//th[contains(@class, 'sortable')]//span[text()='Сумма']"
    COLUMNHEADER_REASON = "//th[contains(@class, 'sortable')]//span[text()='Причина']"
    COLUMNHEADER_USER = "//th[contains(@class, 'sortable')]//span[text()='Пользователь']"
    COLUMNHEADER_ORGANIZATION_DEDUCTION = "//th[contains(@class, 'sortable')]//span[text()='Вычет организация']"
    COLUMNHEADER_EMPLOYEE_DEDUCTION = "//th[contains(@class, 'sortable')]//span[text()='Вычет сотрудник']"
    COLUMNHEADER_ACCOUNT_GROUP = "//th[contains(@class, 'sortable')]//span[text()='Группа счетов']"
    COLUMNHEADER_SPENT_FROM_ACCOUNT = "//th[contains(@class, 'sortable')]//span[text()='Потрачено со счета']"
    COLUMNHEADER_ACCRUED_TO_ACCOUNT = "//th[contains(@class, 'sortable')]//span[text()='Начислено на счет']"
    COLUMNHEADER_CHECKS_SUM_TABLE = "//th[contains(@class, 'sortable')]//span[text()='Сумма чеков']"
    COLUMNHEADER_REMAINDER = "//th[contains(@class, 'sortable')]//span[text()='Остаток']"
    COLUMNHEADER_DATETIME = "//th[contains(@class, 'sortable')]//span[text()='Дата/Время']"
    COLUMNHEADER_IDENTIFIER_TYPE = "//th[contains(@class, 'sortable')]//span[text()='Тип идентификатора']"
    COLUMNHEADER_CASH_REGISTER = "//th[contains(@class, 'sortable')]//span[text()='Касса']"
    COLUMNHEADER_CHECK = "//th[contains(@class, 'sortable')]//span[text()='Чек']"
    COLUMNHEADER_OPERATION = "//th[contains(@class, 'sortable')]//span[text()='Операция']"
    COLUMNHEADER_CODE = "//th[contains(@class, 'sortable')]//span[text()='Код']"
    COLUMNHEADER_TYPE = "//th[contains(@class, 'sortable')]//span[text()='Тип']"
    COLUMNHEADER_COUNT = "//th[contains(@class, 'sortable')]//span[text()='Кол-во']"
    COLUMNHEADER_BIRTH_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата рождения']"
    COLUMNHEADER_AGE = "//th[contains(@class, 'sortable')]//span[text()='Возраст']"
    COLUMNHEADER_TOTAL_CHECKS_PERIOD = "//th[contains(@class, 'sortable')]//span[text()='Всего чеков за период']"
    COLUMNHEADER_AVG_CHECKS_MONTH = "//th[contains(@class, 'sortable')]//span[text()='В среднем чеков в месяц']"
    COLUMNHEADER_AVG_CHECKS_DAY = "//th[contains(@class, 'sortable')]//span[text()='В среднем чеков в день']"
    COLUMNHEADER_TOTAL_SPENDS_PERIOD = "//th[contains(@class, 'sortable')]//span[text()='Всего потрат за период']"
    COLUMNHEADER_AVG_CHECK = "//th[contains(@class, 'sortable')]//span[text()='Средний чек']"
    COLUMNHEADER_LAST_CHECK_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата последнего чека']"
    COLUMNHEADER_BALANCE_START = "//th[contains(@class, 'sortable')]//span[text()='Остаток на начало']"
    COLUMNHEADER_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата']"
    COLUMNHEADER_TOTAL_ALL_SOURCES = "//th[contains(@class, 'sortable')]//span[text()='Суммарно по всем источникам']"
    COLUMNHEADER_CHECKS_COUNT = "//th[contains(@class, 'sortable')]//span[text()='Кол-во чеков']"
    COLUMNHEADER_VISITS_COUNT = "//th[contains(@class, 'sortable')]//span[text()='Кол-во посещений']"
    COLUMNHEADER_SPENDS_SUM = "//th[contains(@class, 'sortable')]//span[text()='Сумма потрат']"
    COLUMNHEADER_DISCOUNTS_SUM = "//th[contains(@class, 'sortable')]//span[text()='Сумма скидок']"
    COLUMNHEADER_COUPON = "//th[contains(@class, 'sortable')]//span[text()='Купон']"
    COLUMNHEADER_START_BALANCE = "//th[contains(@class, 'sortable')]//span[text()='Остаток на начало']"
    COLUMNHEADER_ACCRUED = "//th[contains(@class, 'sortable')]//span[text()='Начислено']"
    COLUMNHEADER_REDEEMED = "//th[contains(@class, 'sortable')]//span[text()='Погашено']"
    COLUMNHEADER_BURNED_BEFORE_REDEMPTION = "//th[contains(@class, 'sortable')]//span[text()='Сгорело до гашения']"
    COLUMNHEADER_END_BALANCE = "//th[contains(@class, 'sortable')]//span[text()='Остаток на конец']"
    COLUMNHEADER_PROMOCODE_NAME = "//th[contains(@class, 'sortable')]//span[text()='Название']"
    COLUMNHEADER_TRIGGER_NAME = "//th[contains(@class, 'sortable')]//span[text()='Название']"

    COLUMNHEADER_PROMOCODE_TYPE = "//th[contains(@class, 'sortable')]//span[text()='Тип']"
    COLUMNHEADER_INPUT_PHRASE = "//th[contains(@class, 'sortable')]//span[text()='Фраза для ввода']"
    COLUMNHEADER_PROMOCODE_START_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата начала']"
    COLUMNHEADER_PROMO_START_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата начала']"
    COLUMNHEADER_PROMOCODE_END_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата окончания']"
    COLUMNHEADER_PROMO_END_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата окончания']"
    COLUMNHEADER_SEGMENT_NAME = "//th[contains(@class, 'sortable')]//span[text()='Название']"
    COLUMNHEADER_ACCOUNTS_COUNT = "//th[contains(@class, 'sortable')]//span[text()='Кол-во счетов']"
    COLUMNHEADER_PERCENT = "//th[contains(@class, 'sortable')]//span[text()='%']"
    COLUMNHEADER_LAST_RECALCULATION = "//th[contains(@class, 'sortable')]//span[text()='Дата/время последнего пересчета']"
    COLUMNHEADER_CREATION_DATE = "//th[contains(@class, 'sortable')]//span[text()='Дата/время создания']"
    COLUMNHEADER_APPLY_DATETIME = "//th[contains(@class, 'sortable')]//span[text()='Дата/Время применения']"
    COLUMNHEADER_ACTION_NAME = "//th[contains(@class, 'sortable')]//span[text()='Название акции']"
    COLUMNHEADER_WHAT_WAS_DONE = "//th[contains(@class, 'sortable')]//span[text()='Что было сделано']"
    COLUMNHEADER_ACTION_DURATION = "//th[contains(@class, 'sortable')]//span[text()='Продолжительность применения акции (сек.)']"
    COLUMNHEADER_TRIGGERS_COUNT = "//th[contains(@class, 'sortable')]//span[text()='Кол-во срабатываний']"
    COLUMNHEADER_RESTAURANT_CODE = "//th[contains(@class, 'sortable')]//span[text()='Код ресторана']"
    COLUMNHEADER_DISCOUNT_CODE_NAME = "//th[contains(@class, 'sortable')]//span[text()='Код / Название скидки']"
    COLUMNHEADER_DISH_CODE_NAME = "//th[contains(@class, 'sortable')]//span[text()='Код / Название блюда']"
    COLUMNHEADER_SEGMENT_TYPE = "//th[contains(@class, 'sortable')]//span[text()='Тип сегмента']"
    COLUMNHEADER_LAST_TRIGGER_TIME = "//th[contains(@class, 'sortable')]//span[text()='Последнее срабатывание']"
    COLUMNHEADER_REGISTERED = "//th[contains(@class, 'sortable')]//span[text()='Зарегистрирован']"
    COLUMNHEADER_PHONES_TABLE = "//th[contains(@class, 'sortable')]//span[text()='Телефоны']"
    COLUMNHEADER_ROLE = "//th[contains(@class, 'sortable')]//span[text()='Роль']"
    COLUMNHEADER_DESCRIPTION ="//th[contains(@class, 'sortable')]//span[text()='Описание']"
    COLUMNHEADER_GRADE = "//th[contains(@class, 'sortable')]//span[text()='Оценка']"
    COLUMNHEADER_RESTAURANTS= "//th[contains(@class, 'sortable')]//span[text()='Ресторан']"
    COLUMNHEADER_NAME_COUP= "//th[contains(@class, 'sortable') and .//span[text()='Наименование']]"
    COLUMNHEADER_TAG_ID = "//th[contains(@class, 'sortable') and contains(@class, 'text-center') and .//span[text()='id']]"

    # Диалоговые окна и заголовки
    DIALOG_ADD_ACCOUNT = "Добавить счёт"
    DIALOG_ADD_ACCOUNT_GROUP = "Добавить группу счетов"
    DIALOG_ADD_COMPOUND_DISCOUNT = "Добавить составную скидку/бонус"
    DIALOG_ADD_USER = "Добавить пользователя"
    DIALOG_ADD_API_USER = "Добавить пользователя API"
    DIALOG_ADD_ROLE ="//span[@class='headline' and normalize-space()='Добавить роль']"

    DIALOG_ADD_PRODUCT_COUPON = "Добавление товарного купона"
    DIALOG_ADD_TAG = "Добавить тег"
    DIALOG_ADD_TAG_GROUP = "Добавить группу тегов"
    DIALOG_ADD_STAMP_ACTION = "Добавить акцию штампики (N+1)"
    DIALOG_ADD_SEGMENT_ACTION = "Добавить акцию"
    DIALOG_ADD_PROMOCODE = "Добавить промокод"
    DIALOG_ADD_TRIGGER_ACTION = "Добавить триггерную акцию"
    DIALOG_ADD_SEGMENT = "Добавить сегмент"
    DIALOG_ADD_IDENTIFIER_TYPE = "Добавить тип идентификатора"
    DIALOG_ADD_RESTAURANT = "Добавить ресторан"
    
    # Тексты для проверки
    TEXT_MAIN = "Основные"
    TEXT_SAVE = "Сохранить"
    TEXT_ACTIONS = "Действия"
    TEXT_EMAIL = "Email"
    TEXT_PHONE = "Телефон"
    TEXT_TAGS = "Теги"
    TEXT_ALL = "Все"
    TEXT_AFTER_REGISTRATION = "После регистрации"
    TEXT_FOREVER = "Бессрочно"
    DATE_LIFE = 'input[type="number"][test-tag="tag-829"]'
    TEXT_YES = "Да"
    TEXT_NO = "Нет"
    TEXT_MALE = "Мужской"
    TEXT_FEMALE = "Женский"
    TEXT_REGISTRATION_CLOSED = "Регистрация закрыта"
    TEXT_SOMETHING_WRONG = "Что-то пошло не так"
    TEXT_ACCOUNT_HIDDEN = "Аккаунт скрыт пользователем"
    TEXT_REVIEW_COMPLETED = "Отзыв завершен"
    TEXT_REVIEW_AUTO_COMPLETED = "Отзыв завершен автоматически"
    TEXT_DO_NOT_SPECIFY = "Не указывать"
    TEXT_COMPLETE_REVIEW = "Завершить отзыв"
    TEXT_CHOOSE_ANOTHER = "Выбрать другой..."
    TEXT_PREVIOUS_PAGE = ">>"
    TEXT_NEXT_PAGE = "<<"
    TEXT_RATING_1 = "⭐ - ужасно"
    TEXT_RATING_2 = "⭐⭐ - плохо"
    TEXT_RATING_3 = "⭐⭐⭐ - приемлемо"
    TEXT_RATING_4 = "⭐⭐⭐⭐ - хорошо"
    TEXT_RATING_5 = "⭐⭐⭐⭐⭐ - отлично"
    TEXT_UNKNOWN_COMMAND = "Неизвестная команда"
    
    # Фразы из Telegram бота (часть 1)
    BOT_ALREADY_REGISTERED = "Уже зарегистрированы"
    BOT_ALREADY_REGISTERED_DEFAULT = "⛔ Вы уже зарегистрированы"
    BOT_POLICY_ALREADY_ACCEPTED = "Политика уже принята"
    BOT_POLICY_ALREADY_ACCEPTED_DEFAULT = "✅ Политика уже принята."
    BOT_PERSONAL_DATA_POLICY_BUTTON = "Кнопка \"Политика обработки персональных данных\""
    BOT_PERSONAL_DATA_POLICY_BUTTON_DEFAULT = "🔐 Политика обработки персональных данных"
    BOT_ACCEPT_PRIVACY_BUTTON_PRESSED = "Нажатая кнопка \"Принять политику конфиденциальности\""
    BOT_ACCEPT_PRIVACY_BUTTON_PRESSED_DEFAULT = "✅ Принять политику конфиденциальности"
    BOT_CONFIRM_AGE_BUTTON_PRESSED = "Нажатая кнопка \"Подтверждаю возраст\""
    BOT_CONFIRM_AGE_BUTTON_PRESSED_DEFAULT = "✅ Подтверждаю, что я старше 18 лет"
    BOT_ACCEPT_PERSONAL_DATA_BUTTON_PRESSED = "Нажатая кнопка \"Принять политику обработки персональных данных\""
    BOT_ACCEPT_PERSONAL_DATA_BUTTON_PRESSED_DEFAULT = "✅ Принять политику обработки персональных данных"
    BOT_ALREADY_STARTED_REGISTRATION = "Вы уже начали процесс регистрации"
    BOT_ALREADY_STARTED_REGISTRATION_DEFAULT = "⛔ Вы уже начали процесс регистрации"
    BOT_SHARE_CONTACT_BUTTON = "Кнопка \"Поделиться контактом\""
    BOT_SHARE_CONTACT_BUTTON_DEFAULT = "📞 Поделиться контактом"
    BOT_WRONG_CONTACT_MESSAGE = "Сообщение с чужим контактом"
    BOT_WRONG_CONTACT_MESSAGE_DEFAULT = "⛔ Присланный контакт не соответствует вашему, попробуйте "
    BOT_REGISTRATION_CLOSED = "Регистрация закрыта"
    BOT_REGISTRATION_CLOSED_DEFAULT = "⛔ Номер телефона не найден в системе лояльности. Для реги"
    BOT_YES_BUTTON = "Кнопка \"Да\""
    BOT_YES_BUTTON_DEFAULT = "✅ Да"
    BOT_NAME_QUESTION_RESPONSE = "Ответ на вопрос об имени из"
    BOT_NAME_QUESTION_RESPONSE_DEFAULT = "👉 Ожидается \"{use_profile_name_button"
    BOT_NAME_VALIDATION_FAILED = "Имя не прошло проверку"
    BOT_NAME_VALIDATION_FAILED_DEFAULT = "⛔ Присланное сообщение не прошло проверку. Введите ваше и"
    BOT_SURNAME_VALIDATION_FAILED = "Фамилия не прошла проверку"
    BOT_SURNAME_VALIDATION_FAILED_DEFAULT = "⛔ Присланное сообщение не прошло проверку. Введите вашу ф"
    BOT_PATRONYMIC_VALIDATION_FAILED = "Отчество не прошло проверку"
    BOT_PATRONYMIC_VALIDATION_FAILED_DEFAULT = "⛔ Присланное сообщение не прошло проверку. Введите ваше о"
    BOT_BIRTHDAY_VALIDATION_FAILED = "День рождения не прошел проверку"
    BOT_BIRTHDAY_VALIDATION_FAILED_DEFAULT = "⛔ Дата не прошла проверку. Проверьте корректность введенн"
    BOT_MALE_BUTTON = "Кнопка \"Мужской\""
    BOT_MALE_BUTTON_DEFAULT = "👨 Мужской"
    BOT_GENDER_VALIDATION_FAILED = "Пол не прошел проверку"
    BOT_GENDER_VALIDATION_FAILED_DEFAULT = "⛔ Ожидается \"{male_button}\" или \"{female_button"
    BOT_REGISTRATION_SUCCESS = "Регистрация прошла успешно"
    BOT_REGISTRATION_SUCCESS_DEFAULT = "Регистрация завершилась успешно! 👍"
    BOT_SOMETHING_WRONG = "Что-то пошло не так"
    BOT_SOMETHING_WRONG_DEFAULT = "⛔ Что-то пошло не так. {try_again}"
    BOT_ACCEPT_POLICIES = "Примите политики"
    BOT_ACCEPT_POLICIES_DEFAULT = "Перед тем, как продолжить, примите политики:"
    BOT_PRIVACY_POLICY_BUTTON = "Кнопка \"Политика конфиденциальности\""
    BOT_PRIVACY_POLICY_BUTTON_DEFAULT = "🔐 Политика конфиденциальности"
    BOT_ACCEPT_PRIVACY_BUTTON = "Кнопка \"Принять политику конфиденциальности\""
    BOT_ACCEPT_PRIVACY_BUTTON_DEFAULT = "⬜ Принять политику конфиденциальности"
    BOT_CONFIRM_AGE_BUTTON = "Кнопка \"Подтверждаю возраст\""
    BOT_CONFIRM_AGE_BUTTON_DEFAULT = "⬜ Подтверждаю, что я старше 18 лет"
    BOT_ACCEPT_PERSONAL_DATA_BUTTON = "Кнопка \"Принять политику обработки персональных данных\""
    BOT_ACCEPT_PERSONAL_DATA_BUTTON_DEFAULT = "⬜ Принять политику обработки персональных данных"
    BOT_GO_TO_REGISTRATION_BUTTON = "Кнопка \"Перейти к регистрации\""
    BOT_GO_TO_REGISTRATION_BUTTON_DEFAULT = "➡️➡️➡️Перейти к регистрации➡️➡️➡️"
    BOT_CONTACT_REQUEST = "Запрос контакта"
    BOT_CONTACT_REQUEST_DEFAULT = "📞 Для продолжения работы необходим ваш контакт. Нажмите "
    BOT_NOT_A_CONTACT_MESSAGE = "Сообщение не является контактом"
    BOT_NOT_A_CONTACT_MESSAGE_DEFAULT = "⛔ Присланное сообщение не является контактом, попробуйте "
    BOT_PHONE_ALREADY_IN_SYSTEM = "Номер телефона уже есть в системе лояльности"
    BOT_PHONE_ALREADY_IN_SYSTEM_DEFAULT = "Проверено успешно - Ваш номер телефона уже есть в системе"
    BOT_USE_TELEGRAM_NAME = "Использовать имя из Telegram?"
    BOT_USE_TELEGRAM_NAME_DEFAULT = "👉 Хотите использовать имя {name"
    BOT_NO_BUTTON = "Кнопка \"Нет\""
    BOT_NO_BUTTON_DEFAULT = "❌ Нет"
    BOT_NAME_REQUEST = "Запрос имени"
    BOT_NAME_REQUEST_DEFAULT = "👉 Введите ваше имя"
    BOT_SURNAME_REQUEST = "Запрос фамилии"
    BOT_SURNAME_REQUEST_DEFAULT = "👉 Введите вашу фамилию"
    BOT_PATRONYMIC_REQUEST = "Запрос отчества"
    BOT_PATRONYMIC_REQUEST_DEFAULT = "👉 Введите ваше отчество."
    BOT_BIRTHDAY_REQUEST = "Запрос дня рождения"
    BOT_BIRTHDAY_REQUEST_DEFAULT = "📅 Введите дату рождения в формате дд.мм.гггг (Например: "
    BOT_GENDER_REQUEST = "Запрос пола"
    BOT_GENDER_REQUEST_DEFAULT = "👥 Выберите пол"
    BOT_FEMALE_BUTTON = "Кнопка \"Женский\""
    BOT_FEMALE_BUTTON_DEFAULT = "👩 Женский"
    BOT_REGISTRATION_STARTED = "Регистрация начата"
    BOT_REGISTRATION_STARTED_DEFAULT = "Регистрация начата... ⏳"
    BOT_RESTART_REGISTRATION = "Начать регистрацию заново"
    BOT_RESTART_REGISTRATION_DEFAULT = "📣 Для того чтобы начать регистрацию заново, введите /"
    
    # Фразы из главного меню
    BOT_ACCOUNT_INFO_BUTTON = "Кнопка \"Информация по счету\""
    BOT_ACCOUNT_INFO_BUTTON_DEFAULT = "📊 Информация по счету"
    BOT_VIRTUAL_CARD_BUTTON = "Кнопка \"Виртуальная карта\""
    BOT_VIRTUAL_CARD_BUTTON_DEFAULT = "💳 Виртуальная карта"
    BOT_PROMOCODES_BUTTON = "Кнопка \"Промокоды\""
    BOT_PROMOCODES_BUTTON_DEFAULT = "🎫 Промокоды"
    BOT_ACCOUNT_BALANCE_BUTTON = "Кнопка \"Баланс счета\""
    BOT_ACCOUNT_BALANCE_BUTTON_DEFAULT = "📇 Баланс счёта"
    BOT_LEAVE_REVIEW_BUTTON = "Кнопка \"Оставить отзыв\""
    BOT_LEAVE_REVIEW_BUTTON_DEFAULT = "📝 Оставить отзыв"
    
    # Фразы из информации по счету
    BOT_WAITING_ACCOUNT_REPORT = "Ожидание отчета по счету"
    BOT_WAITING_ACCOUNT_REPORT_DEFAULT = "Отчет формируется, подождите немного. ⏳"
    BOT_STAMPS_INFO = "Штампики"
    BOT_STAMPS_INFO_DEFAULT = "⏹️ Штампики:"
    BOT_DETAILS_BUTTON = "Кнопка \"Подробнее\""
    BOT_DETAILS_BUTTON_DEFAULT = "Подробнее"
    BOT_CHECK_DETAILS_ACCRUED = "Подробнее по чеку (будет начислено)"
    BOT_CHECK_DETAILS_ACCRUED_DEFAULT = "📄 Чек №{check_number} {check_datetime} Ресторан: {"
    BOT_BONUS_WITHDRAWAL_DETAILS = "Подробнее по изъятию бонусов со счета"
    BOT_BONUS_WITHDRAWAL_DETAILS_DEFAULT = "⏺️ Изъятие бонусов {datetime} Сумма: {sum} Причина: {"
    BOT_DETAILED_ACCOUNT_REPORT = "Подробный отчет по счету"
    BOT_DETAILED_ACCOUNT_REPORT_DEFAULT = "{transactions} Показаны последние 5"
    BOT_SPENT_ON_COMPOUND_DISCOUNT = "Потрачено по составной скидке"
    BOT_SPENT_ON_COMPOUND_DISCOUNT_DEFAULT = "💰 Потрачено: {spentSumDiscountPeriod}"
    BOT_COUPON_INFO = "Информация о купоне"
    BOT_COUPON_INFO_DEFAULT = "{name}. {lifetime}"
    BOT_COUPON_FOREVER = "Купон действует бессрочно"
    BOT_COUPON_FOREVER_DEFAULT = "Действует бессрочно"
    BOT_ACCOUNT_REPORT = "Отчет по счету"
    BOT_ACCOUNT_REPORT_DEFAULT = "🥉 Потрачено за день: {spentSumDay} 🥈 За неделю: {"
    BOT_STAMPS_DETAILED_INFO = "Информация о штампиках"
    BOT_STAMPS_DETAILED_INFO_DEFAULT = "{name}: Куплено {currentTurnCount} из {promoCount}"
    BOT_CHECK_DETAILS = "Подробнее по чеку (начислено)"
    BOT_CHECK_DETAILS_DEFAULT = "📄 Чек №{check_number} {check_datetime} Ресторан: {"
    BOT_ACCOUNT_TOPUP_DETAILS = "Подробнее по пополнению счета"
    BOT_ACCOUNT_TOPUP_DETAILS_DEFAULT = "⏺️ Пополнение счета {datetime} Сумма: {sum} Причина: {"
    BOT_BURNED_BONUSES_DETAILS = "Подробнее по сгоревшим бонусам"
    BOT_BURNED_BONUSES_DETAILS_DEFAULT = "⏺️ Сгорание бонусов {datetime} Сумма: {sum} Причина: {"
    BOT_COMPOUND_DISCOUNT_LEVEL = "Уровень составной скидки"
    BOT_COMPOUND_DISCOUNT_LEVEL_DEFAULT = "🥇 Текущий уровень: {discountLevelName}"
    BOT_COUPONS = "Купоны"
    BOT_COUPONS_DEFAULT = "⏺️ Купоны:"
    BOT_COUPON_VALID_UNTIL = "Купон действует до"
    BOT_COUPON_VALID_UNTIL_DEFAULT = "Действует до {datetime}"
    
    # Фразы просмотра баланса
    BOT_WAITING_BALANCE = "Ожидание баланса счета"
    BOT_WAITING_BALANCE_DEFAULT = "Баланс вычисляется, подождите немного. ⏳"
    BOT_BONUS_BURNING = "Сгорание бонусов"
    BOT_BONUS_BURNING_DEFAULT = "🔥 Сгорание бонусов:"
    BOT_AMOUNT_WONT_BURN = "Сумма не сгорит"
    BOT_AMOUNT_WONT_BURN_DEFAULT = "{sum} не сгорит никогда"
    BOT_AMOUNT_WILL_BE_ACCRUED = "Сумма будет начислена"
    BOT_AMOUNT_WILL_BE_ACCRUED_DEFAULT = "{sumLateIssue} бонусов будет начислено {date}"
    BOT_BONUS_BALANCE = "Баланс бонусов"
    BOT_BONUS_BALANCE_DEFAULT = "🧾 Баланс бонусов: {bonusBalance}"
    BOT_AMOUNT_WILL_BURN = "Сумма сгорит"
    BOT_AMOUNT_WILL_BURN_DEFAULT = "{sum} сгорит {date}"
    BOT_BONUSES_AWAITING_ACCRUAL = "Бонусы ожидают начисления"
    BOT_BONUSES_AWAITING_ACCRUAL_DEFAULT = "⏰ Ожидает начисления: {bonusAwaitingIssue}"
    
    # Фразы виртуальной карты
    BOT_WAITING_VIRTUAL_CARD = "Ожидание виртуальной карты"
    BOT_WAITING_VIRTUAL_CARD_DEFAULT = "Виртуальная карта формируется, подождите немного. ⏳"
    BOT_VIRTUAL_CARD_DETAILED_EXPLANATION = "Расширенное объяснение о виртуальной карте"
    BOT_VIRTUAL_CARD_DETAILED_EXPLANATION_DEFAULT = "💳 Этот QR"
    BOT_VIRTUAL_CARD_BASIC_INFO = "Базовая информация о виртуальной карте"
    BOT_VIRTUAL_CARD_BASIC_INFO_DEFAULT = "⏱️ Код будет действителен {time} минут"
    
    # Фразы из отзывов
    BOT_RESTAURANT_REQUEST = "Запроса ресторана"
    BOT_RESTAURANT_REQUEST_DEFAULT = "Укажите ресторан для отзыва"
    BOT_RATING_REQUEST = "Запрос оценки"
    BOT_RATING_REQUEST_DEFAULT = "👉 Пожалуйста, выберите оценку"
    BOT_REVIEW_REQUEST = "Запроса отзыва"
    BOT_REVIEW_REQUEST_DEFAULT = "📝 Напишите подробнее, можно прикрепить фото"
    BOT_REVIEW_START_MANAGER = "Начало отзыва (менеджерский чат)"
    BOT_REVIEW_START_MANAGER_DEFAULT = "#Отзыв{review_id} {user} Оценка: {grade}"
    BOT_REVIEW_COMPLETED_MANAGER = "Отзыв завершен (менеджерский чат)"
    BOT_REVIEW_COMPLETED_MANAGER_DEFAULT = "👍 #Отзыв{review_id} завершен"
    BOT_REVIEW_AUTO_COMPLETED_MANAGER = "Отзыв завершен автоматически (менеджерский чат"
    BOT_REVIEW_AUTO_COMPLETED_MANAGER_DEFAULT = "👍 #Отзыв{review_id} завершен"
    BOT_CONTINUE_REVIEW_REQUEST = "Запрос продолжения отзыва"
    BOT_CONTINUE_REVIEW_REQUEST_DEFAULT = "✍️ Вы можете продолжить свой отзыв"
    BOT_CONTINUE_REVIEW_ERROR = "Запрос продолжения отзыва"
    BOT_CONTINUE_REVIEW_ERROR_DEFAULT = "Ошибка. Вы попытались отправить что-то кроме текста и кар"
    
    # Фразы промокодов
    BOT_PROMOCODE_INVITATION = "Приглашение к вводу промокода"
    BOT_PROMOCODE_INVITATION_DEFAULT = "Введите промокод"
    
    # Общие фразы
    BOT_REGISTRATION_REQUEST = "Запрос регистрации"
    BOT_REGISTRATION_REQUEST_DEFAULT = "📣 Вы не зарегистрированы. Для начала регистрации введите"
    BOT_CANT_REPLY_FROM_MANAGER_CHAT = "Из менеджерского чата нельзя ответить"
    BOT_CANT_REPLY_FROM_MANAGER_CHAT_DEFAULT = "Из этого чата нельзя ответить гостю. Чтобы ответить - наж"
    BOT_TOO_MANY_REQUESTS = "Слишком частые запросы"
    BOT_TOO_MANY_REQUESTS_DEFAULT = "⏳ Пожалуйста, подождите несколько секунд перед повторным "
    BOT_ERROR = "Ошибка"
    BOT_ERROR_DEFAULT = "⛔ Что-то пошло не так. Ошибка: {error_text}"
    
    # Дополнительные текстовые переменные
    TEXT_PERIOD_LIMITATION = "Ограничение периода накоплений"
    TEXT_MASTER_ADDITION = "Мастер Добавления"
    TEXT_MASTER_ADDITION_DESCRIPTION = "Мастер добавления составной скидки/бонуса"
    TEXT_CONTINUE = "Продолжить"
    TEXT_DISH_CODE = "Код блюда"
    TEXT_DISH_NAME = "Название блюда"
    TEXT_DISCOUNT_CODE_SPIN = "Код скидки"
    TEXT_TAG_GROUP = "Группа"
    TEXT_TAG_NAME = "Название"
    TEXT_TAG_GROUP_NAME = "Название группы"
    TEXT_PORTIONS_BUY = "Порций купить"
    TEXT_GIFT_PORTIONS = "Подарочных порций"
    TEXT_ACTION_TYPE = "Тип"
    TEXT_SEGMENT = "Сегмент"
    TEXT_APPLICATION_TYPE = "Тип применения"
    TEXT_TRIGGER_TIME = "Время срабатывания"
    TEXT_PROMOCODE_PHRASE = "Фраза для ввода"
    TEXT_LOCATION_NAME = "Название точки"
    TEXT_MESSAGE = "Сообщение"
    TEXT_DRIVER = "Драйвер"
    TEXT_SERVER = "Сервер"
    TEXT_DB_USER = "Имя пользователя"
    TEXT_DB_PASSWORD = "Пароль"
    TEXT_CONNECTION_STRING = "Строка подключения"
    TEXT_MID_REF_SERVER = "Адрес mid или ref сервера"
    TEXT_XML_USER = "Имя пользователя XML"
    TEXT_XML_PASSWORD = "Пароль пользователя XML"
    TEXT_ZERO_DISCOUNT_CODE = "Код нулевой скидки"
    TEXT_TOKEN_VALIDITY = "Время действия токенов"
    TEXT_REQUIRED_FIELDS = "Обязательные поля"
    TEXT_TEMP_IDENTIFIER = "Временный идентификатор"
    TEXT_LOCALIZATION = "Локализация"
    TEXT_DAY_CHANGE_TIME = "Время смены суток"
    TEXT_BIRTHDAY_DISPLAY = "Отображение дня рождения гостя на кассе"
    TEXT_SPECIAL_CASES_SETTINGS = "Настройки для особых случаев"
    TEXT_GENDER_REQUIRED = "Пол обязателен ? - Да"
    TEXT_PHONE_REQUIRED = "Телефон обязателен ? - Да"
    TEXT_TEMP_ID_VALIDITY = "Время действия временного идентификатора (мин)"
    TEXT_TEMP_ID_LENGTH = "Длина временного идентификатора"
    TEXT_LANGUAGE = "ЯзыкРусский"
    TEXT_DAY_CHANGE_TIME_VALUE = "Время смены суток17:00"
    TEXT_SHOW_ON_CASH = "Показывать на кассе ? - Да"
    TEXT_DAYS_BEFORE = "Дней до"
    TEXT_DAYS_AFTER = "Дней после"
    TEXT_CASH_REG_SETTINGS = "Настройки"
    TEXT_TOKEN = "Токен"
    TEXT_CASH_USER = "Пользователь"
    TEXT_CASH_LINK = "Кассовая ссылка"
    TEXT_OLD_BOT_MIGRATION = "Перенос данных из старого бота ProBonus"
    TEXT_DB_MIGRATION = "Миграция базы данных"
    TEXT_SETTINGS_MIGRATION = "Миграция настроек"
    TEXT_POLICIES_MIGRATION = "Миграция описания и политик"
    TEXT_DESCRIPTION = "Описание"
    TEXT_PERSONAL_DATA_POLICY = "Политики обработки перс. данных"
    TEXT_SHOW_PERSONAL_DATA_POLICY = "Показывать политику обработки перс. данных? - Да"
    TEXT_PRIVACY_POLICY = "Политика конфиденциальности"
    TEXT_SHOW_PRIVACY_POLICY = "Показывать политику конфиденциальности? - Да"
    TEXT_AGE_RESTRICTIONS = "Ограничения по возрасту"
    TEXT_AGE_CONFIRMATION = "Подтверждение возраста? - Нет"
    TEXT_AGE_REQUEST_TEXT_MODIFICATION = "Текст запроса возраста можно изменить в настройках фраз"
    
    # Разделители и другие тексты
    TEXT_SEPARATOR = "Разделитель; точка с запятой"
    TEXT_RECOGNIZE_FILE = "Попытаться распознать файл"
    TEXT_EXPORT_TO_FILE = "Сохранить в файл"

    # Добавить счет вкладки
    TAB_GUEST_FORM = "Анкета Гостя"
    TAB_PARAMETERS = "Параметры"
    TAB_LOYALTY = "Лояльность"
    TAB_BALANCE = "Баланс"
    TAB_TAGS = "Теги"
    TAB_COUPONS = "Купоны"
    TAB_STAMPS = "Штампики"
    TAB_REFERRAL_PROGRAM = "Реферальная программа"

    TEXTBOX_LOGIN = "Логин"
    ROLE_BUTTON_TEXT = "//div[contains(@class, 'v-select__selections') and .//div[contains(text(), 'Администратор')]]"
    ROLE_FILTER_TEXT = "Администратор"
    ROLE_ADMIN_TEXT = "Администратор"
    PASSWORD_TEXT = "Пароль"
    CONFIRM_PASSWORD_TEXT = "Повтор пароля"
    COMMENTS_TEXT = "Комментарии"
    TOKEN = "Токен" 
    TOKEN_GEN = "Генерировать"
    ADD_EMPLOYER_API = "Добавить Пользователя API"
    NAMEING = "Наименование"
    NAMEING_CUPONE = "input[test-tag='tag-801']"
    DISPLAY_TEXT = "Отображение"
    LOGO_TEXT = "Логотип"
    ARROW_TEXT = "Стрелка"
    TIMEOUT_GUEST_INFO_TEXT = "Таймаут на показ информации о госте (сек.)"
    TIMEOUT_ERROR_TEXT = "Таймаут на показ ошибки (сек.)"
    USE_TOUCH_TEXT = "Использовать тач"
    LOGO_IMAGE_TEXT = "Изображение логотипа"
    LOGO_POSITION_TEXT = "Позиция логотипа"
    USE_TOUCH_SWITCH = "Использовать тач"
    EXIT_TEXT = "Выход"
    HELP = "Помощь"
    INFOKIOSK = "Инфокиоск"
    RESTAURANT_CODE = "Код ресторана" 
    DEFAULT_DATA = "Значение по умолчанию: "
    TEXT_START_DATE = "Начало"
    TEXT_END_DATE = "Конец"
    TEXT_PORTIONS_BUY = "Порций купить"
    TEXT_GIFT_PORTIONS = "Подарочных порций"
    TEXT_DISCOUNT_CODE_SPIN = "Код скидки"
    TEXT_FIELD_TITLE = "Заголовок поля"
    TEXT_AMOUNT = "Сумма"
